{{- $ingestToken := (.Values.ingest).token }}

{{- if not .Values.ingest.providerSecretName }}
{{- if not .Values.ingest.tokenSecretName }}
{{- if not (and .Values.ingest .Values.ingest.token) }}
  {{- if or .Release.IsUpgrade .Release.IsInstall }}
    {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace (print (include "satellite.fullname" .) "-token"))}}
    {{- if not $existingSecret }}
      {{- fail (print "Token value required. Set either ingest.token or ingest.tokenSecretName in values")  }}
    {{- end -}}
    {{- $ingestToken = $existingSecret.data.token | b64dec | quote }}
  {{- end }}
{{- end }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "satellite.fullname" . }}-token
  labels:
    {{- include "satellite.labels" . | nindent 4 }}
  annotations:
    {{- include "satellite.annotations" . | nindent 4 }}
stringData:
  token: {{ $ingestToken }}
{{- end}}
{{- end }}
---
{{- if .Values.integrations }}
  {{- range $key, $value := .Values.integrations }}
    {{- if $value.secret }}
      {{- if not $value.type}}
      {{- fail (print "Integration type not provided for key " $key)}}
      {{- end }}
      {{- if not $key}}
      {{- fail (print "Integration key not provided for type " $value.type)}}
      {{- end }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "satellite.fullname" $ }}-{{ $key }}
  labels:
    {{- include "satellite.labels" $ | nindent 4 }}
  annotations:
    {{- include "satellite.annotations" $ | nindent 4 }}
stringData:
  {{- toYaml $value.secret | nindent 2 }}
---
    {{- end }}
  {{- end }}
{{- end }}
