ingest:
  tokenSecretName: resolve-ingest-token
  host: receiver.dev0.resolve.ai

clusterName: banking
environment: smg-production

integrations:
  grafana:
    type: grafana
    create: true
    secretName: resolve-grafana
    connection:
      url: http://grafana.monitoring.svc.cluster.local:3000
      alertScrapingEnabled: true
  alertmanager-main:
    type: alertManager
    create: true
    connection:
      url: http://alertmanager.monitoring.svc.cluster.local:9093
  elasticsearch-banking:
    type: elasticsearch
    create: true
    connection:
      url: http://elasticsearch.monitoring.svc.cluster.local:9200
      # no auth — xpack security disabled on this cluster
      # index: banking-logs
  loki-banking:
    type: loki
    create: true
    connection:
      url: http://loki.monitoring.svc.cluster.local:3100
