apiVersion: v1
kind: Service
metadata:
  name: msteams-relay
  namespace: monitoring
  labels:
    app: msteams-relay
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: msteams-relay
  ports:
    - port: {{ .Values.msteamsRelay.port }}
      targetPort: {{ .Values.msteamsRelay.port }}
      nodePort: {{ .Values.msteamsRelay.service.nodePort }}
