apiVersion: v1
kind: Service
metadata:
  name: servicenow-mock
  namespace: monitoring
  labels:
    app: servicenow-mock
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: servicenow-mock
  ports:
    - port: {{ .Values.servicenowMock.port }}
      targetPort: {{ .Values.servicenowMock.port }}
      nodePort: {{ .Values.servicenowMock.service.nodePort }}
