apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
  labels:
    app: loki
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  selector:
    app: loki
  type: ClusterIP
  ports:
    - port: 3100
      targetPort: 3100
