apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: alertmanager
  ports:
    - name: web
      port: 9093
      targetPort: 9093
      nodePort: {{ .Values.alertmanager.service.nodePort }}
