apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
  labels:
    app: grafana
    {{- include "monitoring.labels" . | nindent 4 }}
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: banking-prometheus
        access: proxy
        url: http://prometheus.monitoring.svc.cluster.local:9090
        isDefault: true
        jsonData:
          timeInterval: "15s"

      - name: Loki
        type: loki
        uid: banking-loki
        access: proxy
        url: http://loki.monitoring.svc.cluster.local:3100
        jsonData:
          maxLines: 1000
          derivedFields:
            - name: TraceID
              matcherRegex: '"trace_id":"(\w+)"'
              url: '$${__value.raw}'
              datasourceUid: banking-tempo

      - name: Tempo
        type: tempo
        uid: banking-tempo
        access: proxy
        url: http://tempo.monitoring.svc.cluster.local:3200
        jsonData:
          httpMethod: GET
          serviceMap:
            datasourceUid: banking-prometheus
          lokiSearch:
            datasourceUid: banking-loki
          nodeGraph:
            enabled: true
          traceQuery:
            timeShiftEnabled: true
            spanStartTimeShift: '-5m'
            spanEndTimeShift: '5m'
