apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
  labels:
    app: grafana
    {{- include "monitoring.labels" . | nindent 4 }}
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: banking-prometheus
        access: proxy
        url: http://prometheus.monitoring.svc.cluster.local:9090
        isDefault: true
        jsonData:
          timeInterval: "15s"

      - name: Loki
        type: loki
        uid: banking-loki
        access: proxy
        url: http://loki.monitoring.svc.cluster.local:3100
        jsonData:
          maxLines: 1000
