apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  selector:
    app: grafana
  type: {{ .Values.grafana.service.type }}
  ports:
    - port: 3000
      targetPort: 3000
      {{- if eq .Values.grafana.service.type "NodePort" }}
      nodePort: {{ .Values.grafana.service.nodePort }}
      {{- end }}
