{{- if .Values.prometheus.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: monitoring
  labels:
    app: prometheus
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.prometheus.storage.size }}
  {{- if .Values.prometheus.storage.storageClass }}
  storageClassName: {{ .Values.prometheus.storage.storageClass }}
  {{- end }}
{{- end }}
